# Generated by Django 4.0.4 on 2022-06-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nynet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Iva'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total'),
        ),
    ]
