# Generated by Django 4.0.4 on 2022-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nynet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount_invoices',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount of invoices'),
        ),
    ]
