# Generated by Django 4.0.4 on 2022-06-02 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nynet', '0002_invoice_iva_invoice_subtotal_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of invoice'),
        ),
    ]
