# Generated by Django 4.0.4 on 2022-06-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nynet', '0003_invoice_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='price',
        ),
    ]
