# Generated by Django 4.0.4 on 2022-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='aqui', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(default=123, unique=True, verbose_name='Dni'),
        ),
    ]
