# Generated by Django 4.0.4 on 2022-06-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_address_alter_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(default=123456789, unique=True, verbose_name='Dni'),
        ),
    ]
